export const mockData = [
  {
    id: "1",
    title: "Black Clover",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/black-clover/cover.webp",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 152,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "2",
    title: "Bleach",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/bleach/cover.png",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 36,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "3",
    title: "Blue Lock",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/blue-lock/cover.jpg",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 116,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "4",
    title: "Blue Period",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/blue-period/cover.webp",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 921,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "5",
    title: "Boruto Naruto Next Generations",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/boruto-naruto-next-generations/cover.jpg",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 6,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "6",
    title: "Chainsaw Man",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/chainsaw-man/cover.jpg",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 57,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "7",
    title: "Demon Slayer",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/demon-slayer/cover.jpg",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 80,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "8",
    title: "Fire Punch",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/fire-punch/cover.webp",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 1,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "9",
    title: "Love Is War",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/love-is-war/cover.webp",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 11,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "10",
    title: "My Hero Academia",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/my-hero-academia/cover.webp",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 105,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "11",
    title: "One Piece",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/one-piece/cover.webp",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 224,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "12",
    title: "One Punch Man",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/one-punch-man/cover.webp",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 16,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "13",
    title: "Parasyte",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/parasyte/cover.jpg",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 64,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "14",
    title: "Tokyo Ghoul",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/tokyo-ghoul/cover.jpg",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 88,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "15",
    title: "To Your Eternity",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/to-your-eternity/cover.jpg",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 96,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
  {
    id: "16",
    title: "Vinland Saga",
    demographic: "Shonen",
    description:
      "Embark on an epic journey with a young programmer who discovers a world where code comes to life. Battles are fought not with swords, but with algorithms and data structures.",
    author_id: ["author_abc"],
    status: "ongoing",
    cover_image: "/manga/vinland-saga/cover.jpg",
    tags: ["Adventure", "Fantasy", "Action"],
    chapters_count: 100,
    view_count: 2400,
    rating: 8.7,
    save_count: 350,
    release_date: "2024-02-15",
    created_at: "2024-02-15",
  },
];
